/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clases;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author Ariel G
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    private int actual, contador;
    private PanelSecundario panelSecun=null;
    public Main() {
        actual=0;contador=0;
        initComponents();
        anularFlechas();
    }
    public void setActual(int actual){this.actual=actual;}
    public void anularFlechas(){
        if(actual==0){
            btnAtras.setEnabled(false);
            if(contador>0)
                btnAdelante.setEnabled(true);
            else
                btnAdelante.setEnabled(false);
        }else if(actual>0){
            btnAtras.setEnabled(true);
            btnAdelante.setEnabled(false);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelInicio = new javax.swing.JPanel();
        btnInicio = new javax.swing.JButton();
        btnPolTur = new javax.swing.JButton();
        btnTranspPub = new javax.swing.JButton();
        panel1 = new javax.swing.JPanel();
        btnSenorTurista = new javax.swing.JButton();
        btnConsulados = new javax.swing.JButton();
        btnPuntosInfo = new javax.swing.JButton();
        panel2 = new javax.swing.JPanel();
        btnTeleferico = new javax.swing.JButton();
        btnBusCarril = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        fondo = new javax.swing.JLabel();
        setIconImage(new ImageIcon("src/images/icon.png").getImage());
        toolBar = new javax.swing.JToolBar();
        btnSalir = new javax.swing.JButton();
        btnNosotros = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnAtras = new javax.swing.JButton();
        btnAdelante = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        lbTitulo = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        loguito = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Experto");
        getContentPane().setLayout(null);

        PanelInicio.setLayout(null);

        btnInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/inicio1.png"))); // NOI18N
        btnInicio.setToolTipText("");
        btnInicio.setBorderPainted(false);
        btnInicio.setContentAreaFilled(false);
        btnInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInicio.setFocusPainted(false);
        btnInicio.setFocusable(false);
        btnInicio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInicio.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/inicio2.png"))); // NOI18N
        btnInicio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        PanelInicio.add(btnInicio);
        btnInicio.setBounds(10, 100, 370, 130);

        btnPolTur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/policia1.png"))); // NOI18N
        btnPolTur.setToolTipText("Policia turistica");
        btnPolTur.setBorderPainted(false);
        btnPolTur.setContentAreaFilled(false);
        btnPolTur.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPolTur.setFocusPainted(false);
        btnPolTur.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/policia2.png"))); // NOI18N
        btnPolTur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPolTurActionPerformed(evt);
            }
        });
        PanelInicio.add(btnPolTur);
        btnPolTur.setBounds(460, 30, 180, 140);

        btnTranspPub.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tpublico1.png"))); // NOI18N
        btnTranspPub.setToolTipText("Transporte turistico");
        btnTranspPub.setBorderPainted(false);
        btnTranspPub.setContentAreaFilled(false);
        btnTranspPub.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTranspPub.setFocusPainted(false);
        btnTranspPub.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tpublico2.png"))); // NOI18N
        btnTranspPub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTranspPubActionPerformed(evt);
            }
        });
        PanelInicio.add(btnTranspPub);
        btnTranspPub.setBounds(780, 30, 150, 140);

        btnSenorTurista.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSenorTurista.setText("Señor turista");
        btnSenorTurista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSenorTuristaActionPerformed(evt);
            }
        });
        panel1.add(btnSenorTurista);

        btnConsulados.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnConsulados.setText("Consulados");
        btnConsulados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsuladosActionPerformed(evt);
            }
        });
        panel1.add(btnConsulados);

        btnPuntosInfo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnPuntosInfo.setText("Puntos de informacion");
        btnPuntosInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuntosInfoActionPerformed(evt);
            }
        });
        panel1.add(btnPuntosInfo);

        ocultarPanel1();

        PanelInicio.add(panel1);
        panel1.setBounds(460, 180, 220, 60);

        btnTeleferico.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnTeleferico.setText("Teleferico");
        btnTeleferico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelefericoActionPerformed(evt);
            }
        });
        panel2.add(btnTeleferico);

        btnBusCarril.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBusCarril.setText("Bus carril");
        btnBusCarril.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusCarrilActionPerformed(evt);
            }
        });
        panel2.add(btnBusCarril);

        ocultarPanel2();

        PanelInicio.add(panel2);
        panel2.setBounds(760, 180, 190, 50);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Descripción", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jScrollPane1.setViewportView(jTextArea1);

        PanelInicio.add(jScrollPane1);
        jScrollPane1.setBounds(10, 420, 390, 180);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.jpg"))); // NOI18N
        PanelInicio.add(fondo);
        fondo.setBounds(0, 0, 990, 650);

        getContentPane().add(PanelInicio);
        PanelInicio.setBounds(0, 60, 1000, 650);

        toolBar.setRollover(true);

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/salir.png"))); // NOI18N
        btnSalir.setToolTipText("salir");
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.setFocusable(false);
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        toolBar.add(btnSalir);

        btnNosotros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nosotros.png"))); // NOI18N
        btnNosotros.setToolTipText("acerca de nosotros");
        btnNosotros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNosotros.setFocusable(false);
        btnNosotros.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNosotros.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNosotros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNosotrosActionPerformed(evt);
            }
        });
        toolBar.add(btnNosotros);
        toolBar.add(jSeparator1);
        toolBar.add(jSeparator2);

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/atras.png"))); // NOI18N
        btnAtras.setToolTipText("atras");
        btnAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAtras.setFocusable(false);
        btnAtras.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAtras.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        toolBar.add(btnAtras);

        btnAdelante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/adelante.png"))); // NOI18N
        btnAdelante.setToolTipText("adelante");
        btnAdelante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdelante.setFocusable(false);
        btnAdelante.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdelante.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAdelante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdelanteActionPerformed(evt);
            }
        });
        toolBar.add(btnAdelante);
        toolBar.add(jSeparator3);

        lbTitulo.setFont(new java.awt.Font("Tekton Pro Ext", 1, 22)); // NOI18N
        lbTitulo.setText("  TURISMO  EN  LA  CIUDAD  DE  COCHABAMBA  ");
        toolBar.add(lbTitulo);
        toolBar.add(jSeparator4);

        loguito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bolivia.png"))); // NOI18N
        toolBar.add(loguito);

        getContentPane().add(toolBar);
        toolBar.setBounds(0, 0, 1000, 49);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        int resp = JOptionPane.showConfirmDialog(null, "¿Realmente desea salir?", "Confirmación", JOptionPane.YES_NO_OPTION);
        if(resp==0)
            System.exit(0);

    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnNosotrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNosotrosActionPerformed
        // TODO add your handling code here:
        MyIconPersonalizado icon = new MyIconPersonalizado(85,240,"/images/logos.png");
        JOptionPane.showMessageDialog(null, "FACULTAD DE CIENCIAS Y TECNOLOGIA\nUNIVERSIDAD MAYOR DE SAN SIMON"
            + "\nCochabamba - Bolivia"
            + "\n\nIntegrantes:     Morante Nina Nelson Alvaro"
            + "\n                          Poca Huanca Diego Nicolas\n"
            + "\nCarrera:           Ingenieria de Sistemas\n"
            + "\nMateria:           Sistemas Expertos\n"
            + "\nDocente:           Ing. Ayoroa Cardozo Jose Richard\n"
            + "\nGestión:           II - 2016\n", "Acerca de nosotros", JOptionPane.DEFAULT_OPTION, icon);   
    }//GEN-LAST:event_btnNosotrosActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        actual=0;
        contador++;
        anularFlechas();
        panelSecun.setVisible(false);
        PanelInicio.setVisible(true);
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnAdelanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdelanteActionPerformed
        // TODO add your handling code here:
        actual=1;
        contador++;
        anularFlechas();
        PanelInicio.setVisible(false);
        panelSecun.setVisible(true);
    }//GEN-LAST:event_btnAdelanteActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        // TODO add your handling code here:
        crearPanel();
        actual=1;
        anularFlechas();
        PanelInicio.setVisible(false);
        panelSecun.setVisible(true);
        panelSecun.iniciarMotorDeInferencia();
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnPolTurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPolTurActionPerformed
        // TODO add your handling code here:
        ocultarPanel1();
    }//GEN-LAST:event_btnPolTurActionPerformed

    private void btnTranspPubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTranspPubActionPerformed
        // TODO add your handling code here:
        ocultarPanel2();
    }//GEN-LAST:event_btnTranspPubActionPerformed

    private void btnSenorTuristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSenorTuristaActionPerformed
        // TODO add your handling code here:
        MyIconPersonalizado icon = new MyIconPersonalizado(128,128,"/images/preguntas/eva.png");//aqui le doy la direccion de la imagen y el tamaño
            JOptionPane.showMessageDialog(btnSenorTurista, "Señor Turista"
            + "\nlinea1"//modifica aqui
            + "\nlinea2"//modifica aqui
            + "\nlinea3\n"//modifica aqui
                , "Informacion", JOptionPane.DEFAULT_OPTION, icon);
    }//GEN-LAST:event_btnSenorTuristaActionPerformed

    private void btnConsuladosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsuladosActionPerformed
        // TODO add your handling code here:
        MyIconPersonalizado icon = new MyIconPersonalizado(128,128,"/images/preguntas/eva.png");//aqui le doy la direccion de la imagen y el tamaño
            JOptionPane.showMessageDialog(btnConsulados, "Consulados"
            + "\nlinea1"//modifica aqui
            + "\nlinea2"//modifica aqui
            + "\nlinea3\n"//modifica aqui
                , "Informacion", JOptionPane.DEFAULT_OPTION, icon);
    }//GEN-LAST:event_btnConsuladosActionPerformed

    private void btnPuntosInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuntosInfoActionPerformed
        // TODO add your handling code here:
        MyIconPersonalizado icon = new MyIconPersonalizado(128,128,"/images/preguntas/eva.png");//aqui le doy la direccion de la imagen y el tamaño
            JOptionPane.showMessageDialog(btnPuntosInfo, "Puntos de informacion"
            + "\nlinea1"//modifica aqui
            + "\nlinea2"//modifica aqui
            + "\nlinea3\n"//modifica aqui
                , "Informacion", JOptionPane.DEFAULT_OPTION, icon);
    }//GEN-LAST:event_btnPuntosInfoActionPerformed

    private void btnTelefericoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelefericoActionPerformed
        // TODO add your handling code here:
        MyIconPersonalizado icon = new MyIconPersonalizado(128,128,"/images/preguntas/eva.png");//aqui le doy la direccion de la imagen y el tamaño
            JOptionPane.showMessageDialog(btnTeleferico, "Teleferico"
            + "\nlinea1"//modifica aqui
            + "\nlinea2"//modifica aqui
            + "\nlinea3\n"//modifica aqui
                , "Informacion", JOptionPane.DEFAULT_OPTION, icon);
    }//GEN-LAST:event_btnTelefericoActionPerformed

    private void btnBusCarrilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusCarrilActionPerformed
        // TODO add your handling code here:
        MyIconPersonalizado icon = new MyIconPersonalizado(128,128,"/images/preguntas/eva.png");//aqui le doy la direccion de la imagen y el tamaño
            JOptionPane.showMessageDialog(btnBusCarril, "Bus carril"
            + "\nlinea1"//modifica aqui
            + "\nlinea2"//modifica aqui
            + "\nlinea3\n"//modifica aqui
                , "Informacion", JOptionPane.DEFAULT_OPTION, icon);
    }//GEN-LAST:event_btnBusCarrilActionPerformed
    public void crearPanel(){
        panelSecun=new PanelSecundario(this);
        panelSecun.setBounds(0, 60, 1100, 650);
        panelSecun.setVisible(false);
        add(panelSecun);
        anularFlechas();
        
    }
    private void ocultarPanel1(){
        if(panel1.isVisible())
            panel1.setVisible(false);
        else
            panel1.setVisible(true);
    }
    private void ocultarPanel2(){
        if(panel2.isVisible())
            panel2.setVisible(false);
        else
            panel2.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {//RavenGraphiteGlassSkin este es negro
                org.jvnet.substance.SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.GreenMagicSkin");//MistAquaSkin GreenMagicSkin NebulaSkin
                Main m=new Main();
                m.setSize(1010, 730);
                m.setLocationRelativeTo(null);
                //m.setResizable(false);
                m.setVisible(true);
                }catch (Exception e) {}
                }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelInicio;
    private javax.swing.JButton btnAdelante;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnBusCarril;
    private javax.swing.JButton btnConsulados;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnNosotros;
    private javax.swing.JButton btnPolTur;
    private javax.swing.JButton btnPuntosInfo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSenorTurista;
    private javax.swing.JButton btnTeleferico;
    private javax.swing.JButton btnTranspPub;
    private javax.swing.JLabel fondo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel loguito;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JToolBar toolBar;
    // End of variables declaration//GEN-END:variables
}
